### ISSUE TITLE
Error when trying CME2.py

### ISSUE THREAD

**Issue by keg5038** [je-suis-tm/web-scraping#2]
Hello,
Love your work - trying to use it to learn from! 

When I try to run CME2.py, I get the error: "string indices must be integers" & it points to the line output['prior settle']=[i['priorSettle'] for i in df['quotes']]

I am a novice when it comes to webscraping, but hoping you may be able to shed some light on the issue. Thanks so much!

**Comment by je-suis-tm** [comment]
I'm sorry but I didn't get the error when I ran it just now.

1. Have you done a git pull? Make sure you are using the latest version.

2. Have you modified the script? In that case, you have to print out variable `i`,`df`,`output` to figure out where the erreur comes from. Can't help you from my end.
