### ISSUE TITLE
error for the wallstreetbets subreddit scraper 

### ISSUE THREAD

**Issue by sohamdata** [je-suis-tm/web-scraping#24]
had to disable  insecure request warning before running as it showed error. 
```
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
But after running, it throws this error:
```
line 207, in main
    if val[0] == '$' and not val[1].isdigit():
IndexError: string index out of range
```

**Comment by je-suis-tm** [comment]
Hi, I do not really maintain the web scraper. If you go through the entire README document, I am sure you will be able to reconfigure the web scraper. Thanks.
