### ISSUE TITLE
Volume - Front Month Incorrect

### ISSUE THREAD

**Issue by keg5038** [je-suis-tm/web-scraping#4]
Hi!
Great work on this - thanks so much! 
Wanted to point out one small thing  - the 'front month' logic doesn't work as intended, as you're reading those in as a string with commas in the volume numbers. This means it doesn't find the true highest volume, rather the highest volume less than 1,000. 

On my version, I slightly amended the list comprehension to read this:
```
output['volume']=[i['volume'] for i in df['quotes']]
output['volume'] = output['volume'].replace(',','', regex=True).astype(int)
output['front month']=output['volume']==max(output['volume'])
```

This worked as intended, but there's probably a better way. Thanks again!

**Comment by je-suis-tm** [comment]
Hi keg5038, thank you for pointing this out! This is a terrible mistake commited by me. Luckily I don't run a hedge fund on CME future price, or this would've been a multi-million mistake.
