### ISSUE TITLE
Which of the available scrapers can filter by date?

### ISSUE THREAD

**Issue by roshan-k-patel** [je-suis-tm/web-scraping#6]
Hi there,

I came across this repo and wanted to know which if any of the available scrapers can scrape by date? I noticed most of them have been combined into the MENA newsletter.py, and do not see an option to search between dates of any of them. 

I want to scrape a dataset from the last year about specific daily news from a handful of companies for a university project. One of the few resources i found was newsapi.org but it is quite costly to search for news older than 1 month.

**Comment by je-suis-tm** [comment]
Hi roshan-k-patel, sorry for the late reply, unfortunately none. As you can see the query strings in MENA newsletter, most of them use "page". Maybe some of the websites support date in query string, you have to find it out yourself.

**Comment by je-suis-tm** [comment]
Actually there is a workaround if query string does not support date. You can use the scrapers to scrape as many pages as you want, later apply regex to locate the news of specific dates.
