### ISSUE TITLE
wallstreetbets

### ISSUE THREAD

**Issue by nikolaysaev** [je-suis-tm/web-scraping#7]
Hello, I have a problem with the wallstreetbets.py , I am receiving the following error : 

\Python36-32\lib\site-packages\urllib3\connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'new.reddit.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Do you have an idea how to fix it ?

**Comment by je-suis-tm** [comment]
Hi, it seems to me that it's merely a warning not an error? You can always ignore a warning. If it's an error, that probably means you have modified hosts or you are hiding behind a corporate proxy. You need to specify your proxy, username, password and certificates. Check this part of the repository to debug. 

https://github.com/je-suis-tm/web-scraping#1-proxy-authentication

**Comment by je-suis-tm** [comment]
So has the issue been solved? If that's the case, I will close the ticket?
